language: python

python:
    - 3.7
    - 3.6
    - 3.5

cache:
    directories:
     - /home/travis/.sbt/

before_install:
    - mkdir -p $HOME/.sbt/launchers/1.2.1
    - curl -L -o $HOME/.sbt/launchers/1.2.1/sbt-launch.jar https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.1/sbt-launch.jar

install:
  - pip install --upgrade setuptools pip flake8 pytest-cov codecov
  - make lint dist 
  - pip install dist/*.whl coverage
  - pip freeze

script:
  - make test

after_success:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - codecov

after_failure:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
