language: python
python:
    - 3.6
    - 3.5
    - 3.4

install:
  - pip install --upgrade setuptools pip flake8 pytest-cov codecov
  - make lint dist 
  - pip install dist/*.whl coverage
  - pip freeze

script:
  - echo "SKIPPING TESTS UNTIL JUPYTER_KERNEL_MGMT HAS BEEN UPDATED"
  # Skip tests until property jupyter_kernel_mgmt is available
  # - py.test --cov remote_kernel_provider remote_kernel_provider

after_success:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - codecov

after_failure:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
